#ifndef HTTP_RESPONSE_STATUS_CODES_HPP
# define HTTP_RESPONSE_STATUS_CODES_HPP

# define HTTP_RESPONSE_STATUS_CODE_100 "Continue"
# define HTTP_RESPONSE_STATUS_CODE_101 "Switching Protocols"
# define HTTP_RESPONSE_STATUS_CODE_102 "Processing"
# define HTTP_RESPONSE_STATUS_CODE_103 "Early Hints"
# define HTTP_RESPONSE_STATUS_CODE_200 "OK"
# define HTTP_RESPONSE_STATUS_CODE_201 "Created"
# define HTTP_RESPONSE_STATUS_CODE_202 "Accepted"
# define HTTP_RESPONSE_STATUS_CODE_203 "Non-Authoritative Information"
# define HTTP_RESPONSE_STATUS_CODE_204 "No Content"
# define HTTP_RESPONSE_STATUS_CODE_205 "Reset Content"
# define HTTP_RESPONSE_STATUS_CODE_206 "Partial Content"
# define HTTP_RESPONSE_STATUS_CODE_207 "Multi-Status"
# define HTTP_RESPONSE_STATUS_CODE_208 "Already Reported"
# define HTTP_RESPONSE_STATUS_CODE_226 "IM Used"
# define HTTP_RESPONSE_STATUS_CODE_300 "Multiple Choices"
# define HTTP_RESPONSE_STATUS_CODE_301 "Moved Permanently"
# define HTTP_RESPONSE_STATUS_CODE_302 "Found"
# define HTTP_RESPONSE_STATUS_CODE_303 "See Other"
# define HTTP_RESPONSE_STATUS_CODE_304 "Not Modified"
# define HTTP_RESPONSE_STATUS_CODE_305 "Use Proxy"
# define HTTP_RESPONSE_STATUS_CODE_307 "Temporary Redirect"
# define HTTP_RESPONSE_STATUS_CODE_308 "Permanent Redirect"
# define HTTP_RESPONSE_STATUS_CODE_400 "Bad Request"
# define HTTP_RESPONSE_STATUS_CODE_401 "Unauthorized"
# define HTTP_RESPONSE_STATUS_CODE_402 "Payment Required"
# define HTTP_RESPONSE_STATUS_CODE_403 "Forbidden"
# define HTTP_RESPONSE_STATUS_CODE_404 "Not Found"
# define HTTP_RESPONSE_STATUS_CODE_405 "Method Not Allowed"
# define HTTP_RESPONSE_STATUS_CODE_406 "Not Acceptable"
# define HTTP_RESPONSE_STATUS_CODE_407 "Proxy Authentication Required"
# define HTTP_RESPONSE_STATUS_CODE_408 "Request Timeout"
# define HTTP_RESPONSE_STATUS_CODE_409 "Conflict"
# define HTTP_RESPONSE_STATUS_CODE_410 "Gone"
# define HTTP_RESPONSE_STATUS_CODE_411 "Length Required"
# define HTTP_RESPONSE_STATUS_CODE_412 "Precondition Failed"
# define HTTP_RESPONSE_STATUS_CODE_413 "Payload Too Large"
# define HTTP_RESPONSE_STATUS_CODE_414 "URI Too Long"
# define HTTP_RESPONSE_STATUS_CODE_415 "Unsupported Media Type"
# define HTTP_RESPONSE_STATUS_CODE_416 "Range Not Satisfiable"
# define HTTP_RESPONSE_STATUS_CODE_417 "Expectation Failed"
# define HTTP_RESPONSE_STATUS_CODE_418 "I'm a teapot"
# define HTTP_RESPONSE_STATUS_CODE_421 "Misdirected Request"
# define HTTP_RESPONSE_STATUS_CODE_422 "Unprocessable Content"
# define HTTP_RESPONSE_STATUS_CODE_423 "Locked"
# define HTTP_RESPONSE_STATUS_CODE_424 "Failed Dependency"
# define HTTP_RESPONSE_STATUS_CODE_425 "Too Early"
# define HTTP_RESPONSE_STATUS_CODE_426 "Upgrade Required"
# define HTTP_RESPONSE_STATUS_CODE_428 "Precondition Required"
# define HTTP_RESPONSE_STATUS_CODE_429 "Too Many Requests"
# define HTTP_RESPONSE_STATUS_CODE_431 "Request Header Fields Too Large"
# define HTTP_RESPONSE_STATUS_CODE_451 "Unavailable For Legal Reasons"
# define HTTP_RESPONSE_STATUS_CODE_500 "Internal Server Error"
# define HTTP_RESPONSE_STATUS_CODE_501 "Not Implemented"
# define HTTP_RESPONSE_STATUS_CODE_502 "Bad Gateway"
# define HTTP_RESPONSE_STATUS_CODE_503 "Service Unavailable"
# define HTTP_RESPONSE_STATUS_CODE_504 "Gateway Timeout"
# define HTTP_RESPONSE_STATUS_CODE_505 "HTTP Version Not Supported"
# define HTTP_RESPONSE_STATUS_CODE_506 "Variant Also Negotiates"
# define HTTP_RESPONSE_STATUS_CODE_507 "Insufficient Storage"
# define HTTP_RESPONSE_STATUS_CODE_508 "Loop Detected"
# define HTTP_RESPONSE_STATUS_CODE_510 "Not Extended"
# define HTTP_RESPONSE_STATUS_CODE_511 "Network Authentication Required"

#endif
